<?php

namespace App\Actions\Admin;

use App\Actions\BaseAction;
use App\Enum\StatusCode;
use App\Http\Resources\ProductResource;
use App\Http\Resources\UserResource;
use App\Models\Product;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Validator;

class AddProductAction extends BaseAction
{
    protected function validate(array $data)
    {
        Validator::make($data, [
            'name' => 'required',
            'description' => 'required',
            'price' => 'required',
            'quantity' => 'required',
        ])->validate();
    }
    private  function uploadImage()
    {
        if (request()->hasFile('image')) {
            $imagePath = request()->file('image')->store('products', 'public');
        } else {
            $imagePath = null;
        }
        return $imagePath;

    }
    protected function execute(array $data)
    {
        $product=Product::create([
           'name' => $data['name'],
           'description' => $data['description'],
           'price' => $data['price'],
            'quantity' => $data['quantity'],
            'image'=>$this->uploadImage(),
        ]);
        $product->save();
        return $product;
    }
    protected function resource($result): JsonResource
    {
       return new  ProductResource($result);// TODO: Change the autogenerated stub
    }
}
