<?php

namespace App\Actions\Admin;

use App\Actions\BaseAction;
use App\Models\Product;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Validator;

class DeleteProductAction extends BaseAction
{
    protected function validate(array $data)
    {
        Validator::make($data,[
            'id'=>'required',
        ])->validate();// TODO: Change the autogenerated stub
    }
    public  function execute(array $data)
    {
        $product = Product::findorfail($data['id']);
        $product->delete();
        return[ 'message'=>'success'];
    }
    protected function resource($result): JsonResource
    {
        return new JsonResource($result); // TODO: Change the autogenerated stub
    }
}
