<?php

namespace App\Actions\Admin;

use App\Actions\BaseAction;
use App\Http\Resources\ProductResource;
use App\Models\Product;
use Faker\Provider\Base;
use Illuminate\Http\Resources\Json\JsonResource;

class ShowProductAction extends  BaseAction
{
    protected  function  execute( array $data=[])
    {
        $product=Product::all();
        return $product;
    }

    protected function resource($result): JsonResource
    {
        return  ProductResource::collection($result);// TODO: Change the autogenerated stub
    }

}
