<?php

namespace App\Actions\Auth;

use App\Actions\BaseAction;
use App\Http\Resources\UserResource;
use App\Models\User;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Resources\Json\JsonResource;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Validator;

class RegisterAction extends BaseAction
{
    protected function validate(array $data)
    {
        Validator::make($data, [
            'name' => 'required|string',
            'email' => 'required|email|unique:users',
            'password' => 'required|min:6',
        ])->validate();
    }
    protected function execute(array $data)
    {
        $user = User::create([
            'name' => $data['name'],
            'email' => $data['email'],
            'password' => Hash::make($data['password']),
        ]);
        $user->assignRole('User');
       return $user;
    }
    protected function resource($result): JsonResource
    {
        return new UserResource($result);// TODO: Change the autogenerated stub
    }
}
